name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Force xcode 11.4.1
      run: sudo xcode-select -switch /Applications/Xcode_11.4.1.app
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 11' -scheme 'EasySwift-Package'
